//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", ConfigurationName="ServiceReference1.FnrhWs")]
    public interface FnrhWs
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhAtualizarResponse1> fnrhAtualizarAsync(ServiceReference1.fnrhAtualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhCheckinResponse1> fnrhCheckinAsync(ServiceReference1.fnrhCheckinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhCheckoutResponse1> fnrhCheckoutAsync(ServiceReference1.fnrhCheckoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhInserirResponse1> fnrhInserirAsync(ServiceReference1.fnrhInserirRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhAtualizar
    {
        
        private string chaveAcessoField;
        
        private string snNumField;
        
        private fnrhRequest fnrhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveAcesso
        {
            get
            {
                return this.chaveAcessoField;
            }
            set
            {
                this.chaveAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string snNum
        {
            get
            {
                return this.snNumField;
            }
            set
            {
                this.snNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public fnrhRequest fnrh
        {
            get
            {
                return this.fnrhField;
            }
            set
            {
                this.fnrhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhRequest
    {
        
        private string bgstdsccidadeField;
        
        private string bgstdsccidade2Field;
        
        private string bgstdsccidadedestField;
        
        private string bgstdsccidadedest2Field;
        
        private string bgstdscestadoField;
        
        private string bgstdscestadodestField;
        
        private string bgstdscpaisField;
        
        private string bgstdscpaisdestField;
        
        private string chaveAcessoField;
        
        private string noLocalidadeField;
        
        private string sgUfField;
        
        private string sncelulardddField;
        
        private string sncelularddiField;
        
        private string sncelularnumField;
        
        private string sncidaderesField;
        
        private System.DateTime sndtnascimentoField;
        
        private bool sndtnascimentoFieldSpecified;
        
        private string snemailField;
        
        private string snestadoresField;
        
        private string snexcluirfichaField;
        
        private string snidcidadeibgeField;
        
        private string snidcidadeibgedestField;
        
        private string snidcidadeibgeresField;
        
        private string snmotreservaField;
        
        private string snmotviaField;
        
        private string snnacionalidadeField;
        
        private string snnomecompletoField;
        
        private string snnumcpfField;
        
        private string snnumdocField;
        
        private string snnumhospField;
        
        private string snobsField;
        
        private string snocupacaoField;
        
        private string snorgexpField;
        
        private string snpaisresField;
        
        private System.DateTime snpreventField;
        
        private bool snpreventFieldSpecified;
        
        private System.DateTime snprevsaiField;
        
        private bool snprevsaiFieldSpecified;
        
        private string snresidenciaField;
        
        private string snsexoField;
        
        private string sntelefonedddField;
        
        private string sntelefoneddiField;
        
        private string sntelefonenumField;
        
        private string sntipdocField;
        
        private string sntiptranField;
        
        private string snuhnumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bgstdsccidade
        {
            get
            {
                return this.bgstdsccidadeField;
            }
            set
            {
                this.bgstdsccidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bgstdsccidade2
        {
            get
            {
                return this.bgstdsccidade2Field;
            }
            set
            {
                this.bgstdsccidade2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string bgstdsccidadedest
        {
            get
            {
                return this.bgstdsccidadedestField;
            }
            set
            {
                this.bgstdsccidadedestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bgstdsccidadedest2
        {
            get
            {
                return this.bgstdsccidadedest2Field;
            }
            set
            {
                this.bgstdsccidadedest2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string bgstdscestado
        {
            get
            {
                return this.bgstdscestadoField;
            }
            set
            {
                this.bgstdscestadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string bgstdscestadodest
        {
            get
            {
                return this.bgstdscestadodestField;
            }
            set
            {
                this.bgstdscestadodestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string bgstdscpais
        {
            get
            {
                return this.bgstdscpaisField;
            }
            set
            {
                this.bgstdscpaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string bgstdscpaisdest
        {
            get
            {
                return this.bgstdscpaisdestField;
            }
            set
            {
                this.bgstdscpaisdestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string chaveAcesso
        {
            get
            {
                return this.chaveAcessoField;
            }
            set
            {
                this.chaveAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string noLocalidade
        {
            get
            {
                return this.noLocalidadeField;
            }
            set
            {
                this.noLocalidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string sgUf
        {
            get
            {
                return this.sgUfField;
            }
            set
            {
                this.sgUfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string sncelularddd
        {
            get
            {
                return this.sncelulardddField;
            }
            set
            {
                this.sncelulardddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string sncelularddi
        {
            get
            {
                return this.sncelularddiField;
            }
            set
            {
                this.sncelularddiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string sncelularnum
        {
            get
            {
                return this.sncelularnumField;
            }
            set
            {
                this.sncelularnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string sncidaderes
        {
            get
            {
                return this.sncidaderesField;
            }
            set
            {
                this.sncidaderesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime sndtnascimento
        {
            get
            {
                return this.sndtnascimentoField;
            }
            set
            {
                this.sndtnascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sndtnascimentoSpecified
        {
            get
            {
                return this.sndtnascimentoFieldSpecified;
            }
            set
            {
                this.sndtnascimentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string snemail
        {
            get
            {
                return this.snemailField;
            }
            set
            {
                this.snemailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string snestadores
        {
            get
            {
                return this.snestadoresField;
            }
            set
            {
                this.snestadoresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string snexcluirficha
        {
            get
            {
                return this.snexcluirfichaField;
            }
            set
            {
                this.snexcluirfichaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string snidcidadeibge
        {
            get
            {
                return this.snidcidadeibgeField;
            }
            set
            {
                this.snidcidadeibgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string snidcidadeibgedest
        {
            get
            {
                return this.snidcidadeibgedestField;
            }
            set
            {
                this.snidcidadeibgedestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string snidcidadeibgeres
        {
            get
            {
                return this.snidcidadeibgeresField;
            }
            set
            {
                this.snidcidadeibgeresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string snmotreserva
        {
            get
            {
                return this.snmotreservaField;
            }
            set
            {
                this.snmotreservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string snmotvia
        {
            get
            {
                return this.snmotviaField;
            }
            set
            {
                this.snmotviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string snnacionalidade
        {
            get
            {
                return this.snnacionalidadeField;
            }
            set
            {
                this.snnacionalidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string snnomecompleto
        {
            get
            {
                return this.snnomecompletoField;
            }
            set
            {
                this.snnomecompletoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string snnumcpf
        {
            get
            {
                return this.snnumcpfField;
            }
            set
            {
                this.snnumcpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string snnumdoc
        {
            get
            {
                return this.snnumdocField;
            }
            set
            {
                this.snnumdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string snnumhosp
        {
            get
            {
                return this.snnumhospField;
            }
            set
            {
                this.snnumhospField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string snobs
        {
            get
            {
                return this.snobsField;
            }
            set
            {
                this.snobsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string snocupacao
        {
            get
            {
                return this.snocupacaoField;
            }
            set
            {
                this.snocupacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string snorgexp
        {
            get
            {
                return this.snorgexpField;
            }
            set
            {
                this.snorgexpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string snpaisres
        {
            get
            {
                return this.snpaisresField;
            }
            set
            {
                this.snpaisresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public System.DateTime snprevent
        {
            get
            {
                return this.snpreventField;
            }
            set
            {
                this.snpreventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool snpreventSpecified
        {
            get
            {
                return this.snpreventFieldSpecified;
            }
            set
            {
                this.snpreventFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public System.DateTime snprevsai
        {
            get
            {
                return this.snprevsaiField;
            }
            set
            {
                this.snprevsaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool snprevsaiSpecified
        {
            get
            {
                return this.snprevsaiFieldSpecified;
            }
            set
            {
                this.snprevsaiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string snresidencia
        {
            get
            {
                return this.snresidenciaField;
            }
            set
            {
                this.snresidenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string snsexo
        {
            get
            {
                return this.snsexoField;
            }
            set
            {
                this.snsexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string sntelefoneddd
        {
            get
            {
                return this.sntelefonedddField;
            }
            set
            {
                this.sntelefonedddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string sntelefoneddi
        {
            get
            {
                return this.sntelefoneddiField;
            }
            set
            {
                this.sntelefoneddiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string sntelefonenum
        {
            get
            {
                return this.sntelefonenumField;
            }
            set
            {
                this.sntelefonenumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string sntipdoc
        {
            get
            {
                return this.sntipdocField;
            }
            set
            {
                this.sntipdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string sntiptran
        {
            get
            {
                return this.sntiptranField;
            }
            set
            {
                this.sntiptranField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string snuhnum
        {
            get
            {
                return this.snuhnumField;
            }
            set
            {
                this.snuhnumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhInserirResponse
    {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhInserir
    {
        
        private string chaveAcessoField;
        
        private fnrhRequest fnrhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveAcesso
        {
            get
            {
                return this.chaveAcessoField;
            }
            set
            {
                this.chaveAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public fnrhRequest fnrh
        {
            get
            {
                return this.fnrhField;
            }
            set
            {
                this.fnrhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhCheckoutResponse
    {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhCheckout
    {
        
        private string chaveAcessoField;
        
        private string snNumField;
        
        private System.DateTime dataCheckoutField;
        
        private bool dataCheckoutFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveAcesso
        {
            get
            {
                return this.chaveAcessoField;
            }
            set
            {
                this.chaveAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string snNum
        {
            get
            {
                return this.snNumField;
            }
            set
            {
                this.snNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime dataCheckout
        {
            get
            {
                return this.dataCheckoutField;
            }
            set
            {
                this.dataCheckoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataCheckoutSpecified
        {
            get
            {
                return this.dataCheckoutFieldSpecified;
            }
            set
            {
                this.dataCheckoutFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhCheckinResponse
    {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhCheckin
    {
        
        private string chaveAcessoField;
        
        private string snNumField;
        
        private System.DateTime dataCheckinField;
        
        private bool dataCheckinFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveAcesso
        {
            get
            {
                return this.chaveAcessoField;
            }
            set
            {
                this.chaveAcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string snNum
        {
            get
            {
                return this.snNumField;
            }
            set
            {
                this.snNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime dataCheckin
        {
            get
            {
                return this.dataCheckinField;
            }
            set
            {
                this.dataCheckinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataCheckinSpecified
        {
            get
            {
                return this.dataCheckinFieldSpecified;
            }
            set
            {
                this.dataCheckinFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/")]
    public partial class fnrhAtualizarResponse
    {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhAtualizarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhAtualizar fnrhAtualizar;
        
        public fnrhAtualizarRequest()
        {
        }
        
        public fnrhAtualizarRequest(ServiceReference1.fnrhAtualizar fnrhAtualizar)
        {
            this.fnrhAtualizar = fnrhAtualizar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhAtualizarResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhAtualizarResponse fnrhAtualizarResponse;
        
        public fnrhAtualizarResponse1()
        {
        }
        
        public fnrhAtualizarResponse1(ServiceReference1.fnrhAtualizarResponse fnrhAtualizarResponse)
        {
            this.fnrhAtualizarResponse = fnrhAtualizarResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhCheckinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhCheckin fnrhCheckin;
        
        public fnrhCheckinRequest()
        {
        }
        
        public fnrhCheckinRequest(ServiceReference1.fnrhCheckin fnrhCheckin)
        {
            this.fnrhCheckin = fnrhCheckin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhCheckinResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhCheckinResponse fnrhCheckinResponse;
        
        public fnrhCheckinResponse1()
        {
        }
        
        public fnrhCheckinResponse1(ServiceReference1.fnrhCheckinResponse fnrhCheckinResponse)
        {
            this.fnrhCheckinResponse = fnrhCheckinResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhCheckoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhCheckout fnrhCheckout;
        
        public fnrhCheckoutRequest()
        {
        }
        
        public fnrhCheckoutRequest(ServiceReference1.fnrhCheckout fnrhCheckout)
        {
            this.fnrhCheckout = fnrhCheckout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhCheckoutResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhCheckoutResponse fnrhCheckoutResponse;
        
        public fnrhCheckoutResponse1()
        {
        }
        
        public fnrhCheckoutResponse1(ServiceReference1.fnrhCheckoutResponse fnrhCheckoutResponse)
        {
            this.fnrhCheckoutResponse = fnrhCheckoutResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhInserirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhInserir fnrhInserir;
        
        public fnrhInserirRequest()
        {
        }
        
        public fnrhInserirRequest(ServiceReference1.fnrhInserir fnrhInserir)
        {
            this.fnrhInserir = fnrhInserir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnrhInserirResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.ws.snrhos.id2.inf.br/", Order=0)]
        public ServiceReference1.fnrhInserirResponse fnrhInserirResponse;
        
        public fnrhInserirResponse1()
        {
        }
        
        public fnrhInserirResponse1(ServiceReference1.fnrhInserirResponse fnrhInserirResponse)
        {
            this.fnrhInserirResponse = fnrhInserirResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface FnrhWsChannel : ServiceReference1.FnrhWs, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class FnrhWsClient : System.ServiceModel.ClientBase<ServiceReference1.FnrhWs>, ServiceReference1.FnrhWs
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FnrhWsClient() : 
                base(FnrhWsClient.GetDefaultBinding(), FnrhWsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FnrhWsPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FnrhWsClient(EndpointConfiguration endpointConfiguration) : 
                base(FnrhWsClient.GetBindingForEndpoint(endpointConfiguration), FnrhWsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FnrhWsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FnrhWsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FnrhWsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FnrhWsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FnrhWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhAtualizarResponse1> ServiceReference1.FnrhWs.fnrhAtualizarAsync(ServiceReference1.fnrhAtualizarRequest request)
        {
            return base.Channel.fnrhAtualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.fnrhAtualizarResponse1> fnrhAtualizarAsync(ServiceReference1.fnrhAtualizar fnrhAtualizar)
        {
            ServiceReference1.fnrhAtualizarRequest inValue = new ServiceReference1.fnrhAtualizarRequest();
            inValue.fnrhAtualizar = fnrhAtualizar;
            return ((ServiceReference1.FnrhWs)(this)).fnrhAtualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhCheckinResponse1> ServiceReference1.FnrhWs.fnrhCheckinAsync(ServiceReference1.fnrhCheckinRequest request)
        {
            return base.Channel.fnrhCheckinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.fnrhCheckinResponse1> fnrhCheckinAsync(ServiceReference1.fnrhCheckin fnrhCheckin)
        {
            ServiceReference1.fnrhCheckinRequest inValue = new ServiceReference1.fnrhCheckinRequest();
            inValue.fnrhCheckin = fnrhCheckin;
            return ((ServiceReference1.FnrhWs)(this)).fnrhCheckinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhCheckoutResponse1> ServiceReference1.FnrhWs.fnrhCheckoutAsync(ServiceReference1.fnrhCheckoutRequest request)
        {
            return base.Channel.fnrhCheckoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.fnrhCheckoutResponse1> fnrhCheckoutAsync(ServiceReference1.fnrhCheckout fnrhCheckout)
        {
            ServiceReference1.fnrhCheckoutRequest inValue = new ServiceReference1.fnrhCheckoutRequest();
            inValue.fnrhCheckout = fnrhCheckout;
            return ((ServiceReference1.FnrhWs)(this)).fnrhCheckoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.fnrhInserirResponse1> ServiceReference1.FnrhWs.fnrhInserirAsync(ServiceReference1.fnrhInserirRequest request)
        {
            return base.Channel.fnrhInserirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.fnrhInserirResponse1> fnrhInserirAsync(ServiceReference1.fnrhInserir fnrhInserir)
        {
            ServiceReference1.fnrhInserirRequest inValue = new ServiceReference1.fnrhInserirRequest();
            inValue.fnrhInserir = fnrhInserir;
            return ((ServiceReference1.FnrhWs)(this)).fnrhInserirAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FnrhWsPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FnrhWsPort))
            {
                return new System.ServiceModel.EndpointAddress("http://fnrhws.hospedagem.turismo.gov.br/FnrhWs/FnrhWs");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FnrhWsClient.GetBindingForEndpoint(EndpointConfiguration.FnrhWsPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FnrhWsClient.GetEndpointAddress(EndpointConfiguration.FnrhWsPort);
        }
        
        public enum EndpointConfiguration
        {
            
            FnrhWsPort,
        }
    }
}
